# Generated by Django 4.0.2 on 2022-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='suburb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
