# Generated by Django 4.0.2 on 2022-02-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_city_listing_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='eircode',
        ),
    ]
