# Generated by Django 4.0.2 on 2022-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_zipcode_listing_eircode'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lease_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=10),
        ),
    ]
